FROM linuxkit/alpine:0c069d0fd7defddb6e03925fcd4915407db0c9e1 AS mirror

RUN apk add --no-cache go musl-dev build-base

ENV GOPATH=/go
COPY . /go/src/github.com/moby/vpnkit
RUN go-compile.sh /go/src/github.com/moby/vpnkit/go/cmd/vpnkit-forwarder

FROM scratch
ENTRYPOINT []
CMD []
WORKDIR /
COPY --from=mirror /go/bin/vpnkit-forwarder /usr/bin/vpnkit-forwarder
# CMD ["/vpnkit-forwarder"]